=== dsemerald/ehud/ehud/config-inputs/xsd/radio.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xsd:element name="radio">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="coordinates"> <!-- position in grid -->
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="x" type="xsd:byte"/>
							<xsd:element name="y" type="xsd:byte"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="activeFrame" type="xsd:byte"/> <!-- frame when active -->
				<xsd:element name="radioState" type="xsd:byte"/> <!-- radio on/off -->
				<xsd:element name="type" type="xsd:string"/>
				<xsd:element name="antenna"> <!-- antenna characteristics -->
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="transmitter" type="xsd:byte"/>
							<xsd:element name="receiver" type="xsd:byte"/>
							<xsd:element name="towerMounted" type="xsd:byte"/>
							<xsd:element name="antennaLength" type="xsd:short"/>
							<xsd:element name="maxTransmissionPower" type="xsd:short"/>
							<xsd:element name="powerSaverModeOn" type="xsd:byte"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="frequency">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="mode" type="xsd:string"/> <!-- FFR / SFR -->
							<xsd:element name="main" type="xsd:short"/>
							<xsd:element name="fractional" type="xsd:byte"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="autoConfig" type="xsd:string"/>
				<xsd:element name="handoverSNR" type="xsd:float"/> <!-- HO signal to noise ratio -->
				<xsd:element name="cellID" type="xsd:int"/>
				<xsd:element name="network">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="lte" type="xsd:byte"/> <!-- LTE capability -->
							<xsd:element name="g2" type="xsd:byte"/> <!-- 2G capability -->
							<xsd:element name="g3" type="xsd:byte"/> <!-- 3G capability -->
							<xsd:element name="non-3gpp" type="xsd:byte"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== dsemerald/ehud/ehud/config-inputs/xml/radio_30010.xml
<?xml version="1.0" encoding="UTF-8"?>
<radio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="radio.xsd">
	<coordinates>
		<x>135.33</x>
		<y>354.72</y>
	</coordinates>
	<activeFrame>2</activeFrame>
	<cellID>30010</cellID>
	<coordinates>
		<main>0</main>
		<fractional>0</fractional>
	</coordinates>
</radio>

=== dsemerald/ehud/ehud/config-inputs/xml/radio_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<radio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="radio.xsd">
  <coordinates>
    <x>40</x>
    <y>450</y>
  </coordinates>
  <activeFrame>2</activeFrame>
  <radioState>0</radioState>
  <type>type</type>
  <antenna>
    <transmitter>0</transmitter>
    <receiver>0</receiver>
    <towerMounted>0</towerMounted>
    <antennaLength>0</antennaLength>
    <maxTransmissionPower>0</maxTransmissionPower>
    <powerSaverModeOn>0</powerSaverModeOn>
  </antenna>
  <frequency>
    <mode>mode</mode>
    <main>0</main>
    <fractional>0</fractional>
  </frequency>
  <autoConfig>autoConfig</autoConfig>
  <handoverSNR>0.0</handoverSNR>
  <cellID>300122</cellID>
  <network>
    <lte>0</lte>
    <g2>0</g2>
    <g3>0</g3>
    <non-3gpp>0</non-3gpp>
  </network>
</radio>
